# creating 3 ec2 instances and r53 records using ansible

- name: creating ec2 instances and r53 records
  hosts: localhost
  become: yes
  vars:
    zone: malluru.online
    instances:
    - db
    - backend
    - frontend
  tasks:
  - name: creating ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t2.micro
      image_id: ami-041e2ea9402c46c32
      security_group: allow-everything
      tags:
        name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_instances_info

  - name: print output
    ansible.builtin.debug:
      msg: "Output: {{ ec2_instances_info }}"

  - name: creating r53 records
    amazon.aws.route53:
      zone: "{{ zone }}"
      record: "{{ item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances.private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_instances_info.results }}"